sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
  allow_failures:
    - php: 7.4snapshot
install:
  - composer install
script:
  - composer test
